openapi: 3.0.0
info:
  title: Todo-List REST API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api/v1
paths:
  /todo-list:
    get:
      summary: Returns a list of all todo-lists
      responses:
        '200':
          description: A JSON object containing a list of all todo-lists
        '500':
          description: Internal server error
    post:
      summary: Creates a new todo-list
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the new todo-list
              required:
                - name
      responses:
        '200':
          description: A JSON object containing the new todo-list ID and name
        '500':
          description: Internal server error
  /todo-list/{list_id}:
    get:
      summary: Returns all entries of a specific todo-list
      parameters:
        - name: list_id
          in: query
          description: The ID of the todo-list
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A JSON object containing a list of all entries of the specified todo-list
        '404':
          description: Todo-list not found
    delete:
      summary: Deletes a specific todo-list and all its entries
      parameters:
        - name: list_id
          in: path
          description: The ID of the todo-list
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo-list deleted
        '404':
          description: Todo-list not found
        '500':
          description: Internal server error
    patch:
      summary: Updates the name of a specific todo-list
      parameters:
        - name: list_id
          in: path
          description: The ID of the todo-list
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the todo-list
              required:
                - name
      responses:
        '200':
          description: Todo-list name updated
        '404':
          description: Todo-list not found
        '500':
          description: Internal server error
  /todo-list/{list_id}/todo:
    post:
      summary: Adds a new todo to a specific todo-list
      parameters:
        - name: list_id
          in: path
          description: The ID of the todo-list
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  description: The description of the new todo
              required:
                - description
      responses:
        '200':
          description: A JSON object containing the ID and description of the new todo
        '404':
          description: Todo-list not found
        '500':
          description: Internal server error
  /todo/{todo_id}:
    patch:
      summary: Updates a specific todo of a todo-list
      parameters:
        - name: todo_id
          in: path
          description: The ID of the todo
          required: true
      responses:
        '200':
          description: A JSON object containing the ID and description of the new todo
        '404':
          description: Todo-list not found
        '500':
          description: Internal server error
    delete:
      summary: Deletes a specific todo
      parameters:
        - name: todo_id
          in: path
          description: The ID of the todo
          required: true
            schema:
              type: string
      responses:
        '200':
          description: todo deleted
        '404':
          description: todo not found
        '500':
          description: Internal server error